# -*- coding: utf-8 -*-
"""Readable_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-9elUqK_o-Rb8tBpuKNRQvsONjK-Yc8L
"""

#20210403 松原 Cap. 8

def shiritori(word, next_head, words):
    # TODO: ５文字以下のワードが3回連続したら終了
    # ? next_headをどうやって持ってこようとしてる？
    # ? next_headをこの関数の中で定義？
    # ? next_headは1文字の文字列にすると良さそう
    
    is_not_match_head = word[-1] != next_head[0]
    if is_not_match_head:
      print("しりとりになってない！やり直し！")
      return False, ""
    
    elif word[-1] == "ん":
      print("「ん」で終わったので負け")
      break
    elif word in words:
      print("すでに使われてるので負け！")
    return True, 'aaa' #←aaaに意味はある？

def main():
    word = ''
    next_head = ''
    words = []
    while(True):
        print('ワードを入力:')
        word = input().strip()
        jadge, next_head = shiritori(word, next_head, words)
        if not jadge or word == "quit":
            print("NG")
            break
        print("OK")
        words.append(word)

if __name__ == "__main__":
    main()