# -*- coding: utf-8 -*-
"""Readable_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-9elUqK_o-Rb8tBpuKNRQvsONjK-Yc8L
"""

#20210417 松原 Cap. 8

def shiritori(word, next_head, words):
    ## debug用
    #print(word[-1]) 
    #print(len(word))

    is_lose_with_nn = word[-1] == "ん"
    if is_lose_with_nn:
      print("「ん」で終わったので負け！")
      #return False, ""

    # ５文字以下のワードが3回連続したら終了(ここの部分「リーダブル」かな？)
    is_lose_continue_short_words = len(word) <= 5 and \
                                 [ len(word) <= 5 for word in words[-2:] ] == [True, True]
    if is_lose_continue_short_words:
      print("5文字以下が３回連続したので負け！")
      #return False, ""
    
    is_not_match_head = not ((next_head == '') or (word[0] == next_head))
    if is_not_match_head:
      print("しりとりになってない！やり直し！")
      #return False, ""
    
    is_lose_already_used = word in words
    if is_lose_already_used:
      print("すでに使われてるので負け！")
      #return False, ""
    
    return not any([is_lose_with_nn, is_lose_continue_short_words, \
                    is_not_match_head, is_lose_already_used]), word[-1] # wordを引数にnext_headを返す


def main():
    word = ''
    next_head = ''
    words = []
    while(True):
        print('ワードを入力:')
        word = input().strip()
        jadge, next_head = shiritori(word, next_head, words)
        if not jadge or word == "quit": #quitを入力してもis_not_match_headで判定される？>>Falseを返しているだけ
            print("NG")
            break
        print("OK")
        words.append(word)

if __name__ == "__main__":
    main()